name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: List files (debug step)
      run: ls -R

    - name: Compile Java files
      run: javac *.java
